// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api.proto

It has these top-level messages:
	PingMessage
	AuthorizeRequest
	AuthorizeResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingMessage struct {
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *PingMessage) Reset()                    { *m = PingMessage{} }
func (m *PingMessage) String() string            { return proto.CompactTextString(m) }
func (*PingMessage) ProtoMessage()               {}
func (*PingMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PingMessage) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type AuthorizeRequest struct {
	Resource string            `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	Action   string            `protobuf:"bytes,2,opt,name=action" json:"action,omitempty"`
	Context  map[string]string `protobuf:"bytes,3,rep,name=context" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AuthorizeRequest) Reset()                    { *m = AuthorizeRequest{} }
func (m *AuthorizeRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeRequest) ProtoMessage()               {}
func (*AuthorizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthorizeRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *AuthorizeRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *AuthorizeRequest) GetContext() map[string]string {
	if m != nil {
		return m.Context
	}
	return nil
}

type AuthorizeResponse struct {
	Permitted bool `protobuf:"varint,1,opt,name=permitted" json:"permitted,omitempty"`
}

func (m *AuthorizeResponse) Reset()                    { *m = AuthorizeResponse{} }
func (m *AuthorizeResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeResponse) ProtoMessage()               {}
func (*AuthorizeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthorizeResponse) GetPermitted() bool {
	if m != nil {
		return m.Permitted
	}
	return false
}

func init() {
	proto.RegisterType((*PingMessage)(nil), "api.PingMessage")
	proto.RegisterType((*AuthorizeRequest)(nil), "api.AuthorizeRequest")
	proto.RegisterType((*AuthorizeResponse)(nil), "api.AuthorizeResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Judge service

type JudgeClient interface {
	SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error)
	Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error)
}

type judgeClient struct {
	cc *grpc.ClientConn
}

func NewJudgeClient(cc *grpc.ClientConn) JudgeClient {
	return &judgeClient{cc}
}

func (c *judgeClient) SayHello(ctx context.Context, in *PingMessage, opts ...grpc.CallOption) (*PingMessage, error) {
	out := new(PingMessage)
	err := grpc.Invoke(ctx, "/api.Judge/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *judgeClient) Authorize(ctx context.Context, in *AuthorizeRequest, opts ...grpc.CallOption) (*AuthorizeResponse, error) {
	out := new(AuthorizeResponse)
	err := grpc.Invoke(ctx, "/api.Judge/Authorize", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Judge service

type JudgeServer interface {
	SayHello(context.Context, *PingMessage) (*PingMessage, error)
	Authorize(context.Context, *AuthorizeRequest) (*AuthorizeResponse, error)
}

func RegisterJudgeServer(s *grpc.Server, srv JudgeServer) {
	s.RegisterService(&_Judge_serviceDesc, srv)
}

func _Judge_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Judge/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServer).SayHello(ctx, req.(*PingMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Judge_Authorize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JudgeServer).Authorize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Judge/Authorize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JudgeServer).Authorize(ctx, req.(*AuthorizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Judge_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Judge",
	HandlerType: (*JudgeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Judge_SayHello_Handler,
		},
		{
			MethodName: "Authorize",
			Handler:    _Judge_Authorize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x6d, 0x1a, 0xda, 0x2f, 0xb9, 0xfd, 0x16, 0xf1, 0xa2, 0x25, 0x04, 0x17, 0x65, 0x56, 0x75,
	0x13, 0xb4, 0x6e, 0xa4, 0x74, 0x23, 0x22, 0x88, 0x20, 0x48, 0x7c, 0x82, 0x31, 0xbd, 0xc4, 0xc1,
	0x38, 0x13, 0x67, 0x26, 0x6a, 0x7c, 0x3a, 0x1f, 0x4d, 0xf2, 0x57, 0x43, 0x75, 0x37, 0xe7, 0xdc,
	0x39, 0x3f, 0x33, 0x17, 0x7c, 0x5e, 0x88, 0xb8, 0xd0, 0xca, 0x2a, 0x74, 0x79, 0x21, 0xd8, 0x09,
	0xcc, 0xee, 0x85, 0xcc, 0xee, 0xc8, 0x18, 0x9e, 0x11, 0x46, 0xe0, 0x65, 0x9a, 0xc8, 0x0a, 0x99,
	0x85, 0xce, 0xc2, 0x59, 0xfa, 0xc9, 0x0e, 0xb3, 0x2f, 0x07, 0x82, 0xcb, 0xd2, 0x3e, 0x29, 0x2d,
	0x3e, 0x29, 0xa1, 0xd7, 0x92, 0x8c, 0xad, 0x05, 0x9a, 0x8c, 0x2a, 0x75, 0x4a, 0xbd, 0xa0, 0xc7,
	0x38, 0x87, 0x29, 0x4f, 0xad, 0x50, 0x32, 0x1c, 0x37, 0x93, 0x0e, 0xe1, 0x06, 0xfe, 0xa5, 0x4a,
	0x5a, 0xfa, 0xb0, 0xa1, 0xbb, 0x70, 0x97, 0xb3, 0x15, 0x8b, 0xeb, 0x56, 0xfb, 0xde, 0xf1, 0x55,
	0x7b, 0xe9, 0x5a, 0x5a, 0x5d, 0x25, 0xbd, 0x24, 0x5a, 0xc3, 0xff, 0xe1, 0x00, 0x03, 0x70, 0x9f,
	0xa9, 0xea, 0xc2, 0xeb, 0x23, 0x1e, 0xc2, 0xe4, 0x8d, 0xe7, 0x25, 0x75, 0xb1, 0x2d, 0x58, 0x8f,
	0x2f, 0x1c, 0x76, 0x06, 0x07, 0x83, 0x14, 0x53, 0x28, 0x69, 0x08, 0x8f, 0xc1, 0x2f, 0x48, 0xbf,
	0x08, 0x6b, 0x69, 0xdb, 0xd8, 0x78, 0xc9, 0x0f, 0xb1, 0x7a, 0x87, 0xc9, 0x6d, 0xb9, 0xcd, 0x08,
	0x4f, 0xc1, 0x7b, 0xe0, 0xd5, 0x0d, 0xe5, 0xb9, 0xc2, 0xa0, 0x29, 0x3c, 0xf8, 0xb8, 0xe8, 0x17,
	0xc3, 0x46, 0xb8, 0x01, 0x7f, 0x97, 0x86, 0x47, 0x7f, 0xbe, 0x31, 0x9a, 0xef, 0xd3, 0x6d, 0x29,
	0x36, 0x7a, 0x9c, 0x36, 0x5b, 0x3a, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xc8, 0x61, 0xdf, 0x5a,
	0xb2, 0x01, 0x00, 0x00,
}
