// Code generated by protoc-gen-go. DO NOT EDIT.
// source: credential.proto

/*
Package authentication is a generated protocol buffer package.

It is generated from these files:
	credential.proto

It has these top-level messages:
	Credential
*/
package authentication

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Credential struct {
	OrganizationID string `protobuf:"bytes,1,opt,name=OrganizationID" json:"OrganizationID,omitempty"`
	UserID         string `protobuf:"bytes,2,opt,name=UserID" json:"UserID,omitempty"`
}

func (m *Credential) Reset()                    { *m = Credential{} }
func (m *Credential) String() string            { return proto.CompactTextString(m) }
func (*Credential) ProtoMessage()               {}
func (*Credential) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Credential) GetOrganizationID() string {
	if m != nil {
		return m.OrganizationID
	}
	return ""
}

func (m *Credential) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*Credential)(nil), "authentication.Credential")
}

func init() { proto.RegisterFile("credential.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 108 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x2e, 0x4a, 0x4d,
	0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4b, 0x2c,
	0x2d, 0xc9, 0x00, 0x89, 0x24, 0x27, 0x96, 0x64, 0xe6, 0xe7, 0x29, 0xf9, 0x70, 0x71, 0x39, 0xc3,
	0xd5, 0x08, 0xa9, 0x71, 0xf1, 0xf9, 0x17, 0xa5, 0x27, 0xe6, 0x65, 0x56, 0x81, 0x65, 0x3d, 0x5d,
	0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xd0, 0x44, 0x85, 0xc4, 0xb8, 0xd8, 0x42, 0x8b, 0x53,
	0x8b, 0x3c, 0x5d, 0x24, 0x98, 0xc0, 0xf2, 0x50, 0x5e, 0x12, 0x1b, 0xd8, 0x12, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xda, 0x31, 0x0e, 0x70, 0x78, 0x00, 0x00, 0x00,
}
